import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import "../styles/general.sass"
import MainLayout from "@/components/layout/main-layout";
import { Footer } from "@/components/footer/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MainLayout>
          {children}
        </MainLayout>

        
      </body>
    </html>
  );
}
